CREATE TABLE IF NOT EXISTS ROSTER (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TYPE CHARACTER_TYPE AS ENUM('Warrior', 'Rogue', 'Mage');

CREATE TABLE IF NOT EXISTS ABILITY (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    VALUE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHARACTER (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    TYPE CHARACTER_TYPE,
    HP INTEGER NOT NULL,
    BASE_HP INTEGER NOT NULL,
    LEVEL INTEGER NOT NULL,
    ROSTER_ID INTEGER,
    CONSTRAINT ROSTER_FKEY
        FOREIGN KEY (ROSTER_ID)
        REFERENCES ROSTER(ID)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS CHARACTER_ROSTER_ID_IDX
    ON CHARACTER(ROSTER_ID);

CREATE TABLE IF NOT EXISTS CHARACTER_ABILITIES (
    ID SERIAL PRIMARY KEY,
    CHARACTER_ID INTEGER NOT NULL,
    ABILITY INTEGER NOT NULL,
    CONSTRAINT CHARACTER_FKEY
        FOREIGN KEY (CHARACTER_ID)
        REFERENCES CHARACTER(ID)
        ON DELETE CASCADE,
    CONSTRAINT ABILITY_FKEY
        FOREIGN KEY (ABILITY)
        REFERENCES ABILITY(ID)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS CHARACTER_ABILITIES_CHARACTER_ID_IDX
    ON CHARACTER_ABILITIES (CHARACTER_ID);

CREATE INDEX IF NOT EXISTS CHARACTER_ABILITIES_ABILITY_IDX
    ON CHARACTER_ABILITIES (ABILITY);

CREATE TYPE RARITY_TYPE AS ENUM ('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY');

CREATE TABLE IF NOT EXISTS ITEM (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    VALUE INTEGER NOT NULL,
    RARITY RARITY_TYPE
);

CREATE TABLE IF NOT EXISTS QUEST (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    REWARD_GOLD INTEGER NOT NULL,
    MIN_LEVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DUNGEON (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FLOOR (
    ID SERIAL PRIMARY KEY,
    DUNGEON_ID INTEGER NOT NULL,
    FLOOR_NUMBER INTEGER NOT NULL,
    CONSTRAINT DUNGEON_FKEY
        FOREIGN KEY (DUNGEON_ID)
        REFERENCES DUNGEON(ID)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS FLOOR_DUNGEON_ID_IDX
    ON FLOOR (DUNGEON_ID);

