CREATE TYPE CHARACTER_TYPE AS ENUM('Warrior', 'Rogue', 'Mage')

CREATE TABLE ABILITY (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    VALUE INTEGER NOT NULL
);

CREATE TABLE CHARACTER (
    ID SERIAL PRIMARY KEY
    NAME TEXT NOT NULL,
    TYPE CHARACTER_TYPE,
    HP INTEGER NOT NULL,
    LEVEL INTEGER NOT NULL,
    ROSTER_ID INTEGER,
    CONSTRAINT FK_ROSTER
        FOREIGN KEY (ROSTER_ID)
        REFERENCES ROSTER(ID)
);

CREATE TABLE CHARACTER_ABILITIES (
    ID SERIAL PRIMARY KEY,
    CHARACTER_ID INTEGER NOT NULL,
    ABILITY INTEGER NOT NULL,
    CONSTRAINT FK_CHARACTER
        FOREIGN KEY (CHARACTER_ID)
        REFERENCES CHARACTER(ID),
    CONSTRAINT FK_ABILITY
        FOREIGN KEY (ABILITY)
        REFERENCES ABILITY(ID)
);

CREATE TYPE RARITY_TYPE AS ENUM ('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY')

CREATE TABLE ITEM (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    VALUE INTEGER NOT NULL,
    RARITY RARITY_TYPE,
    CONSTRAINT FK_RARITY
        FOREIGN KEY (RARITY)
        REFERENCES RARITY(ID)
);

CREATE TABLE ROSTER (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
);

CREATE TABLE QUEST (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    REWARD_GOLD INTEGER NOT NULL,
    MIN_LEVEL INTEGER NOT NULL
);

CREATE TABLE DUNGEON (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE FLOOR (
    ID SERIAL PRIMARY KEY,
    DUNGEON_ID INTEGER NOT NULL,
    FLOOR_NUMBER INTEGER NOT NULL,
    CONSTRAINT FK_DUNGEON
        FOREIGN KEY (DUNGEON_ID)
        REFERENCES DUNGEON(ID)
);
